server:
  port: 7000
spring:
  application:
    name: test-way
    #配置路由
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

#缩减版
#    gateway:
#      discovery:
#        locator:
#          enabled: true

      routes:
            - id: testway
              uri: lb://Product    #设置一个http://localhost:8472
              order: 1
              predicates:
                - Path=/Product/**
#            - Before=2020-11-28T00:00:00.000+08:00 # 表示在2020前访问
              filters:                     # 过滤器: 可以在请求前或请求后作一些手脚
                - StripPrefix=1
                - Log=true,false
    nacos:
      discovery:
        server-addr: localhost:8848

my:
  jwt:
    #跳过认证的路由
    skip-auth-urls:
      - /ceshi
      - /test

    effective-time: 7d
